### DISCUSSION TITLE
Action panasonic_cc.set_horizontal_swing_mode - How to use it?

### DISCUSSION THREAD

**Discussion by vo5tr0** [sockless-coding/panasonic_cc#340] [Q&A] [answered]
I am struggeling with the set_horizontal_swing_mode action. How do I use it?

I came up with this:

```
action: panasonic_cc.set_horizontal_swing_mode
data:
  entity_id: climate.Klima
  swing_mode: mid
```

Unfortunately it just throws an "Unknown Error"

**Comment by vo5tr0** [comment, marked as answer]
Well... choosing the right entity helps :D

```
action: panasonic_cc.set_horizontal_swing_mode
data:
  entity_id: select.klima_horizontal_swing_mode
  swing_mode: mid
```
