### ISSUE TITLE
Using scene on fly won't work as expected

### ISSUE THREAD

**Issue by olivierSemet** [sockless-coding/panasonic_cc#135]
Scenario: I would like to use automation for stopping my air conditioner when windows are opened and turn it on again when closing the window. Easiest way to achieve it is to create scene on the fly and capture states before opening windows with the snapshot_entities parameter

Automation sample:

```
...
service: scene.create
data:
  scene_id: before_open_windows
  snapshot_entities:
    - climate.living_room
 ... 
```

Unfortunately with the current implementation, air conditioner  will **turn on** when you close the window even if it was off before you opened the window 

Issue comes from that the integration turn on the device when you update the _swing_mode, temprature, preset_mode_ properties:

* https://github.com/sockless-coding/panasonic_cc/blob/master/custom_components/panasonic_cc/panasonic.py#L316
* https://github.com/sockless-coding/panasonic_cc/blob/master/custom_components/panasonic_cc/panasonic.py#L247
* https://github.com/sockless-coding/panasonic_cc/blob/master/custom_components/panasonic_cc/panasonic.py#L258

For _fan mode,_ the behaviour is different, it doesn't turn on the device:

* https://github.com/sockless-coding/panasonic_cc/blob/master/custom_components/panasonic_cc/panasonic.py#L280

As it seems to be the expected behaviour, I won't flag it as a bug but:

* Why changing prop _fan mode_ mode has a different behaviour than others ? 
* Could we define an option to disable auto start (`"power": self.constants.Power.On` ) when changing properties as it is not always the expected behaviour ?

**Comment by sockless-coding** [comment]
Hi @olivierSemet 
I have a vague memory of that the power parameter was required to be set to On for the device to honor the other settings.
My Panasonic is currently not operational (Hopefully I get it fixed soon), so I can not verify this (and it might have changed).

**Comment by olivierSemet** [comment]
HI @sockless-coding, 

Tested this morning with pcomfortcloud app, it works well without turning ON devices:

```
pcomfortcloud <email>  <pwd> get 6
reading from device 'salon' (xxx)
id                       : xxxx
parameters
    temperatureInside    : 18
    temperatureOutside   : 21
    temperature          : 27
    power                : Off
    mode                 : Cool
    fanSpeed             : HighMid
    airSwingHorizontal   : Mid
    airSwingVertical     : DownMid
    eco                  : Auto
    nanoe                : Off
```
```
pcomfortcloud <email>  <pwd>  set -t 21 6
```

```
pcomfortcloud olivier.semet@gmail.com cirvef-makjo7-cazJed get 6
reading from device 'salon' (xxx)
id                       :xxx
parameters
    temperatureInside    : 18
    temperatureOutside   : 21
    temperature          : 27
    power                : Off
    mode                 : Heat
    fanSpeed             : HighMid
    airSwingHorizontal   : Mid
    airSwingVertical     : DownMid
    eco                  : Auto
    nanoe                : Off
```
I tested other parameters than temperature. 

To fix my issue with automations and dynamic scenes, I added an option which I called CONF_ENABLE_AUTO_POWER_ON. By default this option is activated to keep the actual behaviour. It works fine except if you enable this option, there is no way to switch ON devices  on thermostat widgets. I might need to implement a custom component working like the one from the official comfort cloud mobile app. 
I'll do a PR if you're interested by those changes.

**Comment by Tsunami2056** [comment]
**Reviving this**

**Setup:** `panasonic_cc` v2025.5.0 + [Advanced Heating Control](https://github.com/panhans/homeassistant/tree/main/blueprints/automation/panhans) blueprint by panhans. AHC uses `scene.create` / `scene.turn_on` / `scene.delete` to snapshot and restore thermostat state around window-open events.

---

**Step 1 — AHC automation trace: window closes, scene applied**

```yaml
trigger:
  id: temperature_change_window_off
  platform: template
  entity_id: binary_sensor.salon_fenetre_contact
  from_state: 'on'   # window open
  to_state: 'off'    # window closed
  for: 30s

state_window: false              # window confirmed closed
is_scene_apply_trigger: true     # AHC is applying the saved scene
scene_to_apply: scene.salon_cuisine_heating_window
scene_trigger: true
mode: 'off'                      # AHC calculates device should stay OFF                                                                                                                                                                                                                                                 is_legacy_restore: false         # scene-based restore is active

climates_information:
  - entity_id: climate.salon_2
    state: 'off'                 # device is OFF before scene fires
    temperature: 20
    current_temperature: 25
```

AHC correctly determines `mode: 'off'` — the device should not turn on. But it still calls `scene.turn_on` to restore the pre-window state, which triggers `reproduce_state` on the climate entity.                                                                                                              [0/1955]

---

**Step 2 — `aio_panasonic_comfort_cloud` API trace during `reproduce_state` (debug logging enabled)**

```
2026-04-07 19:52:36  POST /deviceStatus/control  {'operate': 0}                    → {"result":0} 
2026-04-07 19:52:49  POST /deviceStatus/control  {'operationMode': 3}               → {"result":0}
2026-04-07 19:52:50  POST /deviceStatus/control  {'temperatureSet': 20.0}           → {"result":0}
2026-04-07 19:52:51  POST /deviceStatus/control  {'ecoMode': 0}                     → {"result":0}
2026-04-07 19:52:53  GET  /deviceStatus/<device> → "operate": 0                 
2026-04-07 19:52:54  POST /deviceStatus/control  {'operate': 0}                    → {"result":0}  
2026-04-07 19:52:55  POST /deviceStatus/control  {'operate': 1, 'fanAutoMode': 0}  → {"result":0}  
2026-04-07 19:52:56  POST /deviceStatus/control  {'operate': 1, 'fanAutoMode': 0}  → {"result":0}  
2026-04-07 19:52:58  POST /deviceStatus/control  {'fanSpeed': 0}                    → {"result":0}
```

Note: setting `input_window_legacy_restore: true` in AHC bypasses the scene mechanism and avoids the issue, but sacrifices proper state restoration.
