### ISSUE TITLE
Unable to call Horizontal Swing

### ISSUE THREAD

**Issue by mvanrooijenjr** [sockless-coding/panasonic_cc#182]
Hello.

I wish to use horizontal swing like you state in your example: Simple Thermostat. Yet your code seems to provide no clue as to how to use this plugin to call upon and track the horizontal swing of a Panasonic AC.

Can you or anyone else give a clue on how to achieve this?

**Comment by mvanrooijenjr** [comment]
Is there someone who can help with this?

**Comment by sockless-coding** [comment]
You can use the service call to change the swing mode
```
service: panasonic_cc.set_horizontal_swing_mode
data:
  entity_id: climate.living_room
  swing_mode: Mid
```
Available modes are: Auto, Left, LeftMid, Mid, RightMid, Right

Or you can wait till the next release where I've added select entities
![image](https://github.com/user-attachments/assets/dc6c301f-9bfd-4232-9b30-958c063c57ff)

**Comment by mvanrooijenjr** [comment]
Awesome! I will await the update. Thanks!

**Comment by sockless-coding** [comment]
@mvanrooijenjr the new v1.1.0 is released with the new swing selectors.

**Comment by mvanrooijenjr** [comment]
Oy! Thansk for this.

But how do I get this to show up in either the Thermostat card or the Simple Thermostat card? Am I missing something?

**Comment by sockless-coding** [comment]
I'm not sure those cards supports adding additional control entities. And the climate entity only has one swing mode setting and isn't really extendable.

**Comment by mvanrooijenjr** [comment]
Ah, I see.

How then do I get everything into one control scheme in a neat way? How do you for instance have your AC controls + the seperate horizontal swing / vertical swing on your dashboard?

**Comment by sockless-coding** [comment]
I haven't spent much time designing it right now I'm just using a [vertical-stack-in-card](https://github.com/ofekashery/vertical-stack-in-card) to merge the cards... 
![image](https://github.com/user-attachments/assets/e048cc07-8845-4bc8-b167-7a9318e7e4db)

don't know if it helps much, but maybe you can use it as a start
```yml
type: custom:vertical-stack-in-card
cards:
  - type: custom:simple-thermostat
    entity: climate.living_room
    header:
      name: Living room
      mode:
        names: true
        headings: false
        icons: true
    control:
      hvac: true
      preset: true
      fan:
        Auto:
          icon: mdi:fan
          name: false
        Low:
          icon: mdi:numeric-1-circle-outline
          name: false
        LowMid:
          icon: mdi:numeric-2-circle-outline
          name: false
        Mid:
          icon: mdi:numeric-3-circle-outline
          name: false
        HighMid:
          icon: mdi:numeric-4-circle-outline
          name: false
        High:
          icon: mdi:numeric-5-circle-outline
          name: false
    layout:
      mode:
        headings: false
  - type: entities
    entities:
      - entity: select.living_room_horizontal_swing_mode
      - entity: select.living_room_vertical_swing_mode
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        entity: switch.living_room_nanoe
        name: Nanoe
      - type: custom:button-card
        entity: switch.10010b0813
        icon: mdi:fan
        name: Ceiling fan
      - type: custom:button-card
        size: 75%
        aspect_ratio: 1/1
        styles:
          card:
            - opacity: 0
      - type: custom:button-card
        size: 75%
        aspect_ratio: 1/1
        styles:
          card:
            - opacity: 0
```
