### ISSUE TITLE
Add fan mode as an entity and action

### ISSUE THREAD

**Issue by yoshz** [sockless-coding/panasonic_cc#349]
### Problem Description

Currently I can only change the fan mode from clicking on the climate entity.
I can not use an automation to change the fan mode because it is not available as an entity or action

### Solution Description

Add fan mode as an entity and action just like swing mode and preset.

**Comment by hapination** [comment]
You should see the attributes of the climate sensor under development tools:
<img width="1072" alt="image" src="https://github.com/user-attachments/assets/5e8e94d8-3e5c-4d02-b959-8b5cd73f6cbd" />

You can use the fan mode (or any attribute by selection the corresponding action) in the automation. The entity to select is the climate device itself:
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/3c2ef9d2-87b5-4ff9-9aa0-dda6a9c998ae" />

Same in yaml:
```
description: ""
mode: single
triggers: []
conditions: []
actions:
  - action: climate.set_fan_mode
    metadata: {}
    data:
      fan_mode: High
    target:
      entity_id: climate.ilpalakerta
```
