### ISSUE TITLE
How to use horizontal swing?

### ISSUE THREAD

**Issue by beMoD** [sockless-coding/panasonic_cc#40]
I love this integration in combination with the simple thermometer. 
I got everything working but I just cannot figure out how to add the horizontal swing to the simple thermometer.
This is my current card config: 
```
    - type: 'custom:simple-thermostat'
      entity: climate.wohnzimmer
      header:
        name: Wohnzimmer
      control:
        hvac: true
        preset:
          _hide_when_off: true
        swing: 
          _hide_when_off: true
        fan: 
          _hide_when_off: true
```
What do I need to add to show a control for the horizontal swing? 

Thanks for your help!
