### ISSUE TITLE
Feature request: support for energy module in 2021.8.0

### ISSUE THREAD

**Issue by maartenhendrix** [sockless-coding/panasonic_cc#49]
Is it possible to add the following sensor attributes to support the new energy integration that is added in HA version 2021.8.0?

https://developers.home-assistant.io/blog/2021/05/25/sensor_attributes/

**Comment by ugoogalizer** [comment]
Agree this would be good to have the three required attributues added to the energy sensor please.  I have been able to hack it for the moment by adding the following to the customize.yaml file: 

```
sensor.aircon_daily_energy:
  state_class: measurement
  last_reset: '1970-01-01T00:00:00+00:00'
  device_class: energy
```
But it's quite the hack because the energy consumption is reset daily by panasonic_cc (I don't know what impact that has yet). I haven't figured out yet what time of day it resets at (local midnight, UTC midnight) nor I don't think we can use templates in a customization so that means it will stay a hack until it can be added to panasonic_cc.

Note: If it resets at the same time every day, then I imagine it could be managed through creating a new attribute on thge sensor and updating it every time the `do_update_energy()` call is made within panasonic.py?
